# This is a basic workflow to help you get started with Actions

name: Wpf CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    #strategy:
    #  matrix:
    #    targetPlatform: [x86]
        
    env:
      Solution_Path: Source\WpfApp\WpfApp.sln
      Wpf_Project_Path: Source\WpfApp\WpfApp\WpfApp.csproj
      Published_Path: 'bin\Release\app.publish\Application Files'
    
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checks-out repository
      uses: actions/checkout@v2
      
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      
    - name: Restore nuget
      run: nuget restore .\source\WpfApp\WpfApp.sln
    
    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
      
    # Build WPF app
    - name: Build WPF app
      #working-directory: Source/WpfApp
      run: msbuild $env:Solution_Path /target:publish /p:Configuration=Release /p:publishDir=published
      
    # Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wpf_exe
        path: ${{env.Published_Path}}
      
   
